# The purpose of this program is to simulate the situation of a gas leak
#scenario 3
def main():
    import turtle
#square 1- big square
    
    turtle.speed('fastest')
    turtle.color('red')
    turtle.forward(300)
    turtle.left(90)
    turtle.forward(300)
    turtle.left(90)
    turtle.forward(300)
    turtle.left(90)
    turtle.forward(300)
    turtle.left(90)
#safety zone 1
    turtle.penup()
    turtle.goto(40,200)
    turtle.pendown()
    turtle.begin_fill()
    turtle.color('green')
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.end_fill()
#safety zone 2
    turtle.penup()
    turtle.goto(140,200)
    turtle.pendown()
    turtle.begin_fill()
    turtle.color('green')
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.end_fill()
#safety zone 3
    turtle.penup()
    turtle.goto(240,200)
    turtle.pendown()
    turtle.begin_fill()
    turtle.color('green')
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.forward(30)
    turtle.left(90)
    turtle.end_fill()
#number safety zones
    turtle.penup()
    turtle.color('black')
    style = ('Courier', 30, 'italic')
    turtle.goto(55,200)
    turtle.pendown()
    turtle.write('1', font=style, align='center')
    turtle.hideturtle()

    turtle.penup()
    turtle.color('black')
    style = ('Courier', 30, 'italic')
    turtle.goto(155,200)
    turtle.pendown()
    turtle.write('2', font=style, align='center')
    turtle.hideturtle()

    turtle.penup()
    turtle.color('black')
    style = ('Courier', 30, 'italic')
    turtle.goto(255,200)
    turtle.pendown()
    turtle.write('3', font=style, align='center')
    turtle.hideturtle()

#worker 1
    turtle.penup()
    turtle.goto(220,20)
    turtle.pendown()
    turtle.begin_fill()
    turtle.color('black')
    turtle.circle(10,360)
    turtle.end_fill()
#worker 2
    turtle.penup()
    turtle.goto(50,130)
    turtle.pendown()
    turtle.begin_fill()
    turtle.color('orange')
    turtle.circle(10,360)
    turtle.end_fill()
#worker 3
    turtle.penup()
    turtle.goto(100,270)
    turtle.pendown()
    turtle.begin_fill()
    turtle.color('blue')
    turtle.circle(10,360)
    turtle.end_fill() 
#contaminated area triangle
    turtle.penup()
    turtle.goto(20,300)
    turtle.pendown()
    turtle.color('red')
    turtle.right(60)
    turtle.forward(220)
    turtle.left(90)
    turtle.forward(195)
#worker 3 to safe zone
    turtle.penup()
    turtle.goto(100,270)
    turtle.pendown()
    turtle.color('blue')
    turtle.right(160)
    turtle.forward(90)
    turtle.begin_fill()
    turtle.color('blue')
    turtle.circle(10,360)
    turtle.end_fill()

main()
